# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default=b'type content', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, b'PRI 1'), (2, b'PRI 2'), (3, b'PRI 3')])),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
