# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180804_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
