# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180804_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
