# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180805_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(choices=[(1, b'PRI 1'), (2, b'PRI 2'), (3, b'PRI 3'), (4, b'PRI 3')], default=4),
        ),
    ]
